# -*- coding: utf-8 -*-
"""PROPER SL2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1raOl9u13HMM4xI06EhbL6P-wqpkAj7Jo
"""

import streamlit as st
import pandas as pd
import numpy as np

# ---------------------------------------------------
# FULL SCREEN LAYOUT
# ---------------------------------------------------
st.set_page_config(
    page_title="Biogas–Coal Blending Emission Calculator",
    layout="wide"
)

# ---------------------------------------------------
# REAL COAL PLANT DATA (FOR COAL EF)
# ---------------------------------------------------
plants_data = [
    {'plant_name':'North Karanpura STPP','coal_tons':7969147,'TSP':23907,'PM10':14344,'PM2.5':12910,'SO2':55784},
    {'plant_name':'Patratu STPP','coal_tons':8229144,'TSP':28802,'PM10':17281,'PM2.5':15553,'SO2':41146},
    {'plant_name':'Tenughat TPS','coal_tons':2233800,'TSP':15637,'PM10':9382,'PM2.5':8444,'SO2':13403},
    {'plant_name':'Talcher Kaniha','coal_tons':10704720,'TSP':42819,'PM10':25691,'PM2.5':23122,'SO2':85638},
    {'plant_name':'Darlipali','coal_tons':8563776,'TSP':29117,'PM10':17470,'PM2.5':15723,'SO2':33913},
    {'plant_name':'IB Thermal','coal_tons':9493650,'TSP':34177,'PM10':20506,'PM2.5':18456,'SO2':28196},
    {'plant_name':'Korba Super Thermal','coal_tons':9825216,'TSP':29476,'PM10':17685,'PM2.5':15917,'SO2':29181},
    {'plant_name':'Sipat Super Thermal','coal_tons':10233432,'TSP':34794,'PM10':20876,'PM2.5':18789,'SO2':50655}
]

df_plants = pd.DataFrame(plants_data)

pollutants = ["TSP", "PM10", "PM2.5", "SO2"]

# ---------------------------------------------------
# COAL EMISSION FACTORS (tons pollutant / ton coal)
# ---------------------------------------------------
coal_EF = {
    pol: (df_plants[pol] / df_plants["coal_tons"]).mean()
    for pol in pollutants
}

# ---------------------------------------------------
# BIOGAS EMISSION FACTORS (kg/ton → tons/ton)
# ---------------------------------------------------
biogas_EF_literature = {
    "TSP":   [0.040, 0.045, 0.050, 0.055, 0.048],
    "PM10":  [0.035, 0.040, 0.045, 0.050, 0.042],
    "PM2.5": [0.015, 0.018, 0.020, 0.022, 0.017],
    "SO2":   [0.006, 0.008, 0.010, 0.012, 0.009],
}

biogas_EF = {pol: np.mean(vals)/1000 for pol, vals in biogas_EF_literature.items()}

# ---------------------------------------------------
# CONTROL SYSTEM DEGRADATION (5%)
# ---------------------------------------------------
CONTROL_DEGRADATION = 0.95

# ---------------------------------------------------
# UI
# ---------------------------------------------------
st.title("Biogas–Coal Blending Emission Calculator")
st.subheader("Realistic emission reductions with control-system degradation")

st.markdown("---")

col1, col2 = st.columns(2)

with col1:
    coal_consumption = st.number_input(
        "Annual fuel requirement (tons/year)",
        min_value=0.0,
        value=1_000_000.0
    )

with col2:
    biogas_frac = st.slider(
        "Biogas blending fraction",
        0.0, 1.0, 0.2, 0.05
    )

coal_frac = 1 - biogas_frac

# ---------------------------------------------------
# BASELINE EMISSIONS
# ---------------------------------------------------
st.markdown("### Baseline Coal Emissions (tons/year)")

col3, col4, col5, col6 = st.columns(4)

with col3:
    TSP_in = st.number_input("TSP", min_value=0.0, value=0.0)
with col4:
    PM10_in = st.number_input("PM10", min_value=0.0, value=0.0)
with col5:
    PM25_in = st.number_input("PM2.5", min_value=0.0, value=0.0)
with col6:
    SO2_in = st.number_input("SO₂", min_value=0.0, value=0.0)

baseline = {
    "TSP": TSP_in if TSP_in > 0 else coal_EF["TSP"] * coal_consumption,
    "PM10": PM10_in if PM10_in > 0 else coal_EF["PM10"] * coal_consumption,
    "PM2.5": PM25_in if PM25_in > 0 else coal_EF["PM2.5"] * coal_consumption,
    "SO2": SO2_in if SO2_in > 0 else coal_EF["SO2"] * coal_consumption
}

# ---------------------------------------------------
# CONTROL SYSTEM INPUTS
# ---------------------------------------------------
st.markdown("### Pollution Control Systems")

col7, col8 = st.columns(2)

with col7:
    ESP = st.slider("ESP efficiency (%)", 0, 100, 90)

with col8:
    FGD = st.slider("FGD efficiency (%)", 0, 100, 70)

effective_ESP = (ESP / 100) * CONTROL_DEGRADATION
effective_FGD = (FGD / 100) * CONTROL_DEGRADATION

# ---------------------------------------------------
# CALCULATIONS
# ---------------------------------------------------
results = {}

for pol in baseline:
    # Coal emissions reduced ONLY by blending
    coal_emissions = baseline[pol] * coal_frac

    # Biogas emissions
    biogas_emissions = biogas_EF[pol] * coal_consumption * biogas_frac

    total = coal_emissions + biogas_emissions

    # Controls apply ONLY to incremental benefit
    if biogas_frac > 0:
        if pol in ["TSP", "PM10", "PM2.5"]:
            total += baseline[pol] * biogas_frac * (1 - effective_ESP)

        if pol == "SO2":
            total += baseline[pol] * biogas_frac * (1 - effective_FGD)

    results[pol] = total

# ---------------------------------------------------
# OUTPUT TABLE
# ---------------------------------------------------
df_out = pd.DataFrame({
    "Pollutant": baseline.keys(),
    "Coal Share (%)": coal_frac * 100,
    "Biogas Share (%)": biogas_frac * 100,
    "Baseline Emissions (t/y)": baseline.values(),
    "Post-Blend Emissions (t/y)": results.values(),
    "Reduction (%)": [
        round((1 - results[p] / baseline[p]) * 100, 2)
        for p in baseline
    ]
})

st.markdown("## Final Results")
st.dataframe(df_out, use_container_width=True)

# ---------------------------------------------------
# SUMMARY
# ---------------------------------------------------
st.markdown("## Summary")

st.info(
    f"""
    • **Biogas blending applied:** {biogas_frac*100:.1f}%
    • **ESP & FGD efficiencies internally reduced by 5%**
    • **No reduction shown at 0% biogas blending**
    """
)