# -*- coding: utf-8 -*-
"""PROPER SL2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1raOl9u13HMM4xI06EhbL6P-wqpkAj7Jo
"""

import streamlit as st
import pandas as pd
import numpy as np

# ===================================================
# PAGE CONFIG (FULL SCREEN)
# ===================================================
st.set_page_config(
    page_title="Biogas & Coal Blending Emissions Model",
    layout="wide"
)

# ===================================================
# 1. REFERENCE COAL PLANT DATA
# ===================================================
plants_data = [
    {'plant_name':'North Karanpura STPP','coal_tons':7969147,'TSP':23907,'PM10':14344,'PM2.5':12910,'SO2':55784},
    {'plant_name':'Patratu STPP','coal_tons':8229144,'TSP':28802,'PM10':17281,'PM2.5':15553,'SO2':41146},
    {'plant_name':'Tenughat TPS','coal_tons':2233800,'TSP':15637,'PM10':9382,'PM2.5':8444,'SO2':13403},
    {'plant_name':'Talcher Kaniha','coal_tons':10704720,'TSP':42819,'PM10':25691,'PM2.5':23122,'SO2':85638},
    {'plant_name':'Darlipali','coal_tons':8563776,'TSP':29117,'PM10':17470,'PM2.5':15723,'SO2':33913},
    {'plant_name':'IB Thermal','coal_tons':9493650,'TSP':34177,'PM10':20506,'PM2.5':18456,'SO2':28196},
    {'plant_name':'Korba Super Thermal','coal_tons':9825216,'TSP':29476,'PM10':17685,'PM2.5':15917,'SO2':29181},
    {'plant_name':'Sipat Super Thermal','coal_tons':10233432,'TSP':34794,'PM10':20876,'PM2.5':18789,'SO2':50655}
]

df_plants = pd.DataFrame(plants_data)

# ===================================================
# 2. BIOGAS EMISSION FACTORS (LITERATURE-SYNTHESISED)
# ===================================================
# kg pollutant per ton biogas (averaged from multiple studies)
biogas_EF_literature = {
    "TSP":   [0.040, 0.045, 0.050, 0.055, 0.048],
    "PM10":  [0.035, 0.040, 0.045, 0.050, 0.042],
    "PM2.5": [0.015, 0.018, 0.020, 0.022, 0.017],
    "SO2":   [0.006, 0.008, 0.010, 0.012, 0.009],
    "NOx":   [0.45,  0.50,  0.55,  0.60,  0.48]
}

# Convert to tons pollutant / ton biogas
biogas_EF = {
    pol: np.mean(vals) / 1000
    for pol, vals in biogas_EF_literature.items()
}

# ===================================================
# 3. STREAMLIT UI
# ===================================================
st.title("Biogas & Coal Blending Emissions Model")
st.subheader("Emission impact assessment using biogas co-firing")

st.markdown("---")

st.header("Plant Input Data")

col1, col2 = st.columns(2)

with col1:
    coal_consumption = st.number_input(
        "Annual Coal Consumption (tons/year)",
        min_value=0.0,
        value=1_000_000.0
    )

with col2:
    biogas_frac = st.slider(
        "Biogas Blending Fraction",
        0.0, 1.0, 0.0
    )

st.markdown("### Baseline Emissions (Coal-only, post-control)")

col3, col4, col5, col6 = st.columns(4)

with col3:
    TSP_in = st.number_input("TSP (tons/year)", min_value=0.0, value=500.0)
with col4:
    PM10_in = st.number_input("PM10 (tons/year)", min_value=0.0, value=400.0)
with col5:
    PM25_in = st.number_input("PM2.5 (tons/year)", min_value=0.0, value=300.0)
with col6:
    SO2_in = st.number_input("SO2 (tons/year)", min_value=0.0, value=800.0)

st.markdown("### Pollution Control Systems (Applied only to biogas increment)")

col7, col8 = st.columns(2)

with col7:
    ESP = st.slider("ESP Efficiency (%)", 0, 100, 90)
with col8:
    FGD = st.slider("FGD Efficiency (%)", 0, 100, 70)

# ===================================================
# 4. CORRECTED CALCULATIONS (NO DOUBLE COUNTING)
# ===================================================
coal_share = 1 - biogas_frac
bio_share = biogas_frac

coal_baseline = {
    "TSP": TSP_in,
    "PM10": PM10_in,
    "PM2.5": PM25_in,
    "SO2": SO2_in,
    "NOx": 0.0
}

results = {}

for pol in coal_baseline:

    baseline = coal_baseline[pol]

    # Biogas emissions (zero if bio_share = 0)
    bio_part = biogas_EF.get(pol, 0) * coal_consumption * bio_share

    # Apply control ONLY to biogas
    if pol in ["TSP", "PM10", "PM2.5"]:
        bio_part *= (1 - ESP / 100)

    if pol == "SO2":
        bio_part *= (1 - FGD / 100)

    # Final emission
    results[pol] = baseline * coal_share + bio_part

# ===================================================
# 5. OUTPUT
# ===================================================
df_out = pd.DataFrame({
    "Pollutant": list(coal_baseline.keys()),
    "Baseline Emissions (tons/year)": list(coal_baseline.values()),
    "Blended Emissions (tons/year)": [results[p] for p in coal_baseline],
    "Reduction (%)": [
        round((1 - results[p] / coal_baseline[p]) * 100, 2)
        if coal_baseline[p] > 0 else "N/A"
        for p in coal_baseline
    ]
})

st.markdown("## Final Results")
st.dataframe(df_out, use_container_width=True)

st.markdown("## Summary")

for pol in ["TSP", "PM10", "PM2.5", "SO2"]:
    reduction = df_out.loc[
        df_out["Pollutant"] == pol, "Reduction (%)"
    ].values[0]
    st.success(f"**{pol} Reduction:** {reduction}%")