# -*- coding: utf-8 -*-
"""PROPER SL2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1raOl9u13HMM4xI06EhbL6P-wqpkAj7Jo
"""

import streamlit as st
import pandas as pd
import numpy as np

# ---------------------------------------------------
# FULL SCREEN LAYOUT
# ---------------------------------------------------
st.set_page_config(
    page_title="Biogas–Coal Blending Emission Calculator",
    layout="wide"
)

# ---------------------------------------------------
# REAL COAL PLANT DATA (REFERENCE ONLY)
# ---------------------------------------------------
plants_data = [
    {'plant_name':'North Karanpura STPP','coal_tons':7969147,'TSP':23907,'PM10':14344,'PM2.5':12910,'SO2':55784},
    {'plant_name':'Patratu STPP','coal_tons':8229144,'TSP':28802,'PM10':17281,'PM2.5':15553,'SO2':41146},
    {'plant_name':'Tenughat TPS','coal_tons':2233800,'TSP':15637,'PM10':9382,'PM2.5':8444,'SO2':13403},
    {'plant_name':'Talcher Kaniha','coal_tons':10704720,'TSP':42819,'PM10':25691,'PM2.5':23122,'SO2':85638},
    {'plant_name':'Darlipali','coal_tons':8563776,'TSP':29117,'PM10':17470,'PM2.5':15723,'SO2':33913},
    {'plant_name':'IB Thermal','coal_tons':9493650,'TSP':34177,'PM10':20506,'PM2.5':18456,'SO2':28196},
    {'plant_name':'Korba Super Thermal','coal_tons':9825216,'TSP':29476,'PM10':17685,'PM2.5':15917,'SO2':29181},
    {'plant_name':'Sipat Super Thermal','coal_tons':10233432,'TSP':34794,'PM10':20876,'PM2.5':18789,'SO2':50655}
]

df_plants = pd.DataFrame(plants_data)

# ---------------------------------------------------
# LITERATURE-AVERAGED BIOGAS EMISSION FACTORS
# (kg pollutant / ton biogas)
# ---------------------------------------------------
biogas_EF_literature = {
    "TSP":   [0.040, 0.045, 0.050, 0.055, 0.048],
    "PM10":  [0.035, 0.040, 0.045, 0.050, 0.042],
    "PM2.5": [0.015, 0.018, 0.020, 0.022, 0.017],
    "SO2":   [0.006, 0.008, 0.010, 0.012, 0.009],
    "NOx":   [0.45,  0.50,  0.55,  0.60,  0.48]
}

# Convert to tons/ton (fixed values used internally)
biogas_EF = {pol: np.mean(vals)/1000 for pol, vals in biogas_EF_literature.items()}

# ---------------------------------------------------
# REALISTIC CONTROL SYSTEM DEGRADATION (5%)
# ---------------------------------------------------
CONTROL_DEGRADATION = 0.95

# ---------------------------------------------------
# STREAMLIT UI
# ---------------------------------------------------
st.title("Biogas–Coal Blending Emission Calculator")
st.subheader("Plant-level emission impact assessment with realistic control-system performance")

st.markdown("---")

col1, col2 = st.columns(2)

with col1:
    coal_consumption = st.number_input(
        "Annual fuel requirement (tons/year)",
        min_value=0.0,
        value=1_000_000.0
    )

with col2:
    biogas_frac = st.slider(
        "Biogas blending fraction",
        min_value=0.0,
        max_value=1.0,
        value=0.2,
        step=0.05
    )

coal_frac = 1 - biogas_frac

st.markdown("### Baseline Coal Emissions (tons/year)")

col3, col4, col5, col6 = st.columns(4)

with col3:
    TSP_in = st.number_input("TSP", min_value=0.0, value=500.0)
with col4:
    PM10_in = st.number_input("PM10", min_value=0.0, value=400.0)
with col5:
    PM25_in = st.number_input("PM2.5", min_value=0.0, value=300.0)
with col6:
    SO2_in = st.number_input("SO₂", min_value=0.0, value=800.0)

st.markdown("### Pollution Control Systems")

col7, col8 = st.columns(2)

with col7:
    ESP = st.slider("ESP efficiency (%)", 0, 100, 90)

with col8:
    FGD = st.slider("FGD efficiency (%)", 0, 100, 70)

# ---------------------------------------------------
# EFFECTIVE EFFICIENCIES (WITH 5% PENALTY)
# ---------------------------------------------------
effective_ESP = (ESP / 100) * CONTROL_DEGRADATION
effective_FGD = (FGD / 100) * CONTROL_DEGRADATION

# ---------------------------------------------------
# CALCULATIONS
# ---------------------------------------------------
baseline = {
    "TSP": TSP_in,
    "PM10": PM10_in,
    "PM2.5": PM25_in,
    "SO2": SO2_in,
    "NOx": 0.0
}

results = {}

for pol in baseline:
    coal_part = baseline[pol] * coal_frac
    bio_part = biogas_EF.get(pol, 0) * coal_consumption * biogas_frac
    total = coal_part + bio_part

    if pol in ["TSP", "PM10", "PM2.5"]:
        total *= (1 - effective_ESP)

    if pol == "SO2":
        total *= (1 - effective_FGD)

    results[pol] = total

# ---------------------------------------------------
# OUTPUT TABLE
# ---------------------------------------------------
df_out = pd.DataFrame({
    "Pollutant": baseline.keys(),
    "Coal Share (%)": [coal_frac * 100] * len(baseline),
    "Biogas Share (%)": [biogas_frac * 100] * len(baseline),
    "Baseline Emissions (t/y)": baseline.values(),
    "Post-Blend Emissions (t/y)": results.values(),
    "Reduction (%)": [
        round((1 - results[p] / baseline[p]) * 100, 2) if baseline[p] > 0 else "N/A"
        for p in baseline
    ]
})

st.markdown("## Final Results")
st.dataframe(df_out, use_container_width=True)

# ---------------------------------------------------
# SUMMARY
# ---------------------------------------------------
st.markdown("## Summary")

st.info(
    f"""
    **Fuel Mix:** {coal_frac*100:.1f}% Coal + {biogas_frac*100:.1f}% Biogas
    **ESP & FGD performance reduced by 5%** to reflect real operating conditions.
    """
)

for pol in ["TSP", "PM10", "PM2.5", "SO2"]:
    reduction = df_out.loc[df_out["Pollutant"] == pol, "Reduction (%)"].values[0]
    st.success(f"**{pol} Reduction:** {reduction}%")