# -*- coding: utf-8 -*-
"""sl2 tetstingng1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1viX6vjrVhdMyS7vh-r9uFp2-xS6P2Fde
"""

import streamlit as st
import pandas as pd
import numpy as np

# ---------------------------------------------------
# FULL SCREEN LAYOUT
# ---------------------------------------------------
st.set_page_config(
    page_title="Biogas–Coal Blending Emission Calculator",
    layout="wide"
)

# ---------------------------------------------------
# REFERENCE COAL PLANT DATA (USED TO DERIVE COAL EF)
# ---------------------------------------------------
plants_data = [
    {'coal_tons':7969147,'TSP':23907,'PM10':14344,'PM2.5':12910,'SO2':55784},
    {'coal_tons':8229144,'TSP':28802,'PM10':17281,'PM2.5':15553,'SO2':41146},
    {'coal_tons':2233800,'TSP':15637,'PM10':9382,'PM2.5':8444,'SO2':13403},
    {'coal_tons':10704720,'TSP':42819,'PM10':25691,'PM2.5':23122,'SO2':85638},
    {'coal_tons':8563776,'TSP':29117,'PM10':17470,'PM2.5':15723,'SO2':33913},
    {'coal_tons':9493650,'TSP':34177,'PM10':20506,'PM2.5':18456,'SO2':28196},
    {'coal_tons':9825216,'TSP':29476,'PM10':17685,'PM2.5':15917,'SO2':29181},
    {'coal_tons':10233432,'TSP':34794,'PM10':20876,'PM2.5':18789,'SO2':50655}
]

df = pd.DataFrame(plants_data)

# ---------------------------------------------------
# COAL EMISSION FACTORS (tons pollutant / ton coal)
# ---------------------------------------------------
pollutants = ["TSP", "PM10", "PM2.5", "SO2"]
coal_EF = {p: (df[p] / df["coal_tons"]).mean() for p in pollutants}

# ---------------------------------------------------
# BIOGAS EMISSION FACTORS (literature-averaged)
# kg pollutant / ton biogas → converted to tons/ton
# ---------------------------------------------------
biogas_EF_lit = {
    "TSP":   [0.040, 0.045, 0.050, 0.055, 0.048],
    "PM10":  [0.035, 0.040, 0.045, 0.050, 0.042],
    "PM2.5": [0.015, 0.018, 0.020, 0.022, 0.017],
    "SO2":   [0.006, 0.008, 0.010, 0.012, 0.009],
}

biogas_EF = {p: np.mean(v)/1000 for p, v in biogas_EF_lit.items()}

# ---------------------------------------------------
# CONTROL SYSTEM DEGRADATION (REALISTIC)
# ---------------------------------------------------
CONTROL_DEGRADATION = 0.95  # 5% loss when blending fuels

# ---------------------------------------------------
# STREAMLIT UI
# ---------------------------------------------------
st.title("Biogas–Coal Blending Emission Calculator")
st.subheader("Realistic plant-level emission assessment")

st.markdown("---")

col1, col2 = st.columns(2)

with col1:
    coal_consumption = st.number_input(
        "Annual fuel input (tons/year)",
        min_value=0.0,
        value=1_000_000.0
    )

with col2:
    biogas_frac = st.slider(
        "Biogas blending fraction",
        0.0, 1.0, 0.2, 0.05
    )

coal_frac = 1 - biogas_frac

st.markdown("### Pollution Control Systems")

col3, col4 = st.columns(2)

with col3:
    ESP = st.slider("ESP efficiency (%)", 0, 100, 90)

with col4:
    FGD = st.slider("FGD efficiency (%)", 0, 100, 70)

# ---------------------------------------------------
# APPLY 5% PENALTY ONLY WHEN BIOGAS > 0
# ---------------------------------------------------
if biogas_frac > 0:
    eff_ESP = (ESP / 100) * CONTROL_DEGRADATION
    eff_FGD = (FGD / 100) * CONTROL_DEGRADATION
    penalty_text = "⚠️ ESP & FGD efficiencies reduced by 5% due to fuel blending"
else:
    eff_ESP = ESP / 100
    eff_FGD = FGD / 100
    penalty_text = "ℹ️ No efficiency penalty applied (100% coal operation)"

# ---------------------------------------------------
# BASELINE (100% COAL)
# ---------------------------------------------------
baseline = {
    p: coal_EF[p] * coal_consumption
    for p in pollutants
}

# ---------------------------------------------------
# BLENDED EMISSIONS (PHYSICALLY CORRECT)
# ---------------------------------------------------
results = {}

for p in pollutants:
    coal_em = coal_EF[p] * coal_consumption * coal_frac
    bio_em = biogas_EF[p] * coal_consumption * biogas_frac
    total_raw = coal_em + bio_em

    if p in ["TSP", "PM10", "PM2.5"]:
        total = total_raw * (1 - eff_ESP)
    else:  # SO2
        total = total_raw * (1 - eff_FGD)

    results[p] = total

# ---------------------------------------------------
# OUTPUT TABLE
# ---------------------------------------------------
df_out = pd.DataFrame({
    "Pollutant": pollutants,
    "Coal Share (%)": [coal_frac*100]*4,
    "Biogas Share (%)": [biogas_frac*100]*4,
    "Baseline Emissions (t/y)": [baseline[p] for p in pollutants],
    "Post-Blend Emissions (t/y)": [results[p] for p in pollutants],
    "Reduction (%)": [
        round((1 - results[p]/baseline[p])*100, 2)
        if biogas_frac > 0 else 0.0
        for p in pollutants
    ]
})

st.markdown("## Results")
st.dataframe(df_out, use_container_width=True)

# ---------------------------------------------------
# SUMMARY
# ---------------------------------------------------
st.markdown("## Interpretation")

st.info(
    f"""
    **Fuel Mix:** {coal_frac*100:.1f}% Coal + {biogas_frac*100:.1f}% Biogas
    {penalty_text}

    Emission reductions are **non-linear** due to:
    • Non-zero biogas emission factors
    • Realistic ESP & FGD efficiencies
    • Additional 5% degradation during fuel blending
    """
)

for p in pollutants:
    st.success(f"**{p} Reduction:** {df_out[df_out['Pollutant']==p]['Reduction (%)'].values[0]}%")